name: Deploy Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd azure-function
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create zip of Azure Function app
        run: |
          cd azure-function
          zip -r functionapp.zip .

      - name: Deploy to Azure Function App using Zip Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: sda-bootcamp-func
          package: ./azure-function/functionapp.zip
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
